name: shopify-checkout

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/shopify-checkout/**'

jobs:
  shopify-checkout:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    defaults:
      run:
        working-directory: packages/shopify-checkout

    steps:
      - name: Checkout ğŸ›
        uses: actions/checkout@v2

      - name: Setup node env ğŸ—
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies ğŸ“¦
        run: npm i

      - name: Run tests ğŸ§ª
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: packages/shopify-checkout
          test-script: npm run test:ci -- --json --outputFile="report.json"
          threshold: 80
