name: shopify-checkout

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/shopify-checkout/**'

jobs:
  shopify-checkout:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    defaults:
      run:
        working-directory: packages/shopify-checkout

    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v2

      - name: Setup node env ðŸ—
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies ðŸ“¦
        run: npm i

      - name: Run tests ðŸ§ª
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: packages/shopify-checkout
          test-script: npm run test:ci -- --json --outputFile="report.json"
          threshold: 80
      - name: Shopify Checkout - npm run test:coverage
        if: steps.changes.outputs.shopify-checkout == 'true'
        run: npm run test:coverage
        working-directory: packages/shopify-checkout

      - name: Analyze with SonarCloud
        if: steps.changes.outputs.shopify-checkout == 'true'
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: packages/shopify-checkout
          args: >
            -Dsonar.organization=getnacelle
            -Dsonar.projectKey=getnacelle_preview-data_service_shopify-checkout
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources=src
            -Dsonar.exclusions=src/**/*.test.ts
            -Dsonar.tests=src
            -Dsonar.test.inclusions=src/**/*.test.ts
